### ISSUE TITLE
how do i build it

### ISSUE THREAD

**Issue by terraria99** [shutterbug2000/3DeSmume#6]
i cant build with the build.bat or with the make command
i have included the output of the .bat witch was is the same location as the makefile
[output.txt](https://github.com/shutterbug2000/3DeSmume/files/325068/output.txt)

**Comment by terraria99** [comment]
it been 7 days and no ones commented

**Comment by shutterbug2000** [comment]
We moved development to this repo:
https://github.com/masterfeizz/DeSmuME

and in order to fix that issue, you need to get the 3DS portlibs.

**Comment by terraria99** [comment]
thanks
